services:
  vue-app:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    environment:
      - NODE_ENV=development
    volumes:
      - ./vueApp/vue-sample:/usr/src/app
    command: sh -c "npm run dev"
    ports:
      - "8080:5173"